In [4]:
import pandas as pd

In [5]:
s =pd.Series([23,4,5,6])
s

0    23
1     4
2     5
3     6
dtype: int64

In [4]:
s.values

array([23,  4,  5,  6])

In [ ]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
s.name="calories"
s

0    23
1     4
2     5
3     6
Name: calories, dtype: int64

In [ ]:
# ilco
s.iloc[[1,2]]

1    4
2    5
Name: numbers, dtype: int64

In [ ]:
index=["banana","orange","apple","grape"]
index

['banana', 'orange', 'apple', 'grape']

In [ ]:
s.index=index
s

banana    23
orange     4
apple      5
grape      6
Name: calories, dtype: int64

In [ ]:
# loc
s.loc["apple"]

np.int64(5)

In [ ]:
# dictionaries
fruits={
    "banana":23,
    "orange":14,
    "apple":15,
    "grape":6
}
fruits

{'banana': 23, 'orange': 14, 'apple': 15, 'grape': 6}

In [ ]:
fru =pd.Series(fruits,name="calories")
fru

banana    23
orange    14
apple     15
grape      6
Name: calories, dtype: int64

In [ ]:
fru["orange":"grape"]

orange    14
apple     15
grape      6
Name: calories, dtype: int64

In [ ]:
fru[fru >10]

banana    23
orange    14
apple     15
Name: calories, dtype: int64

# **Logical Operators**

In [ ]:
# and
fru[(fru >10) & (fru <15)]

orange    14
Name: calories, dtype: int64

In [ ]:
# or
fru[(fru >10) | (fru<10)]

banana    23
orange    14
apple     15
grape      6
Name: calories, dtype: int64

In [ ]:
# not
fru[~(fru >10)]

grape    6
Name: calories, dtype: int64

In [41]:
import numpy as np
data={
    "Name":["Abebe","Abel","Beti","David","Blen","Abebe"],
    "Age":[23,45,56,32,np.nan,23],
    "Department":["IT","HR","Finance","IT",np.nan,"IT"],
    "Salary":[2000,3000,4300,5900,3400,2000]
}

In [42]:
df=pd.DataFrame(data)
df

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1   Abel  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900
4   Blen   NaN        NaN    3400
5  Abebe  23.0         IT    2000

In [ ]:
df.head()

    Name  Age Department  Salary
0  Abebe   23         IT    2000
1   Abel   45         HR    3000
2   Beti   56    Finance    4300
3  David   32         IT    5900

In [ ]:
df.tail(2)

    Name  Age Department  Salary
2   Beti   56    Finance    4300
3  David   32         IT    5900

In [ ]:
# loc
df.loc[1:3,["Age","Department"]]

   Age Department
1   45         HR
2   56    Finance
3   32         IT

In [ ]:
# iloc
df.iloc[2:4]

    Name  Age Department  Salary
2   Beti   56    Finance    4300
3  David   32         IT    5900

In [ ]:
df.iloc[2:4,:3]

    Name  Age Department
2   Beti   56    Finance
3  David   32         IT

In [ ]:
df["Age"]

0    23
1    45
2    56
3    32
Name: Age, dtype: int64

In [ ]:
df.drop("Age",axis=1)

    Name Department  Salary
0  Abebe         IT    4000
1   Abel         HR    5000
2   Beti    Finance    6300
3  David         IT    7900
4   Blen        NaN    5400

In [19]:
df

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1  Abebe  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900
4   Blen   NaN        NaN    3400

In [ ]:
df.shape

(5, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         4 non-null      float64
 2   Department  4 non-null      object
 3   Salary      5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

             Age       Salary
count   4.000000     5.000000
mean   39.000000  3720.000000
std    14.491377  1472.073368
min    23.000000  2000.000000
25%    29.750000  3000.000000
50%    38.500000  3400.000000
75%    47.750000  4300.000000
max    56.000000  5900.000000

In [ ]:
# broadcasting

df["Salary"]=df["Salary"] + 1000
df["Salary"]

0    3000
1    4000
2    5300
3    6900
4    4400
Name: Salary, dtype: int64

In [ ]:
df['Age'].unique()

array([23., 45., 56., 32., nan])

In [ ]:
df['Department'].unique()

array(['IT', 'HR', 'Finance', nan], dtype=object)

In [ ]:
df['Department'].value_counts()

Department
IT         2
HR         1
Finance    1
Name: count, dtype: int64

# **Data Cleaning**

In [7]:
df.isnull().sum()

Name          0
Age           1
Department    1
Salary        0
dtype: int64

In [8]:
df.dropna()

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1   Abel  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900

In [10]:
df['Age'].fillna(df['Age'].mean())

0    23.0
1    45.0
2    56.0
3    32.0
4    39.0
Name: Age, dtype: float64

In [11]:
df['Salary'].fillna(df['Salary'].median())

0    2000
1    3000
2    4300
3    5900
4    3400
Name: Salary, dtype: int64

In [12]:
# forward filling
df.fillna(method="ffill")

/tmp/ipykernel_704/3469609267.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1   Abel  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900
4   Blen  32.0         IT    3400

In [17]:
# backward Filling
df.fillna(method="bfill")

/tmp/ipykernel_704/2632034678.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1  Abebe  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900
4   Blen   NaN        NaN    3400

In [18]:
df

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1  Abebe  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900
4   Blen   NaN        NaN    3400

In [22]:
# replace specific value
df['Name']=df['Name'].replace("Abel","Yeshi")
df['Name']

0    Abebe
1    Yeshi
2     Beti
3    David
4     Blen
Name: Name, dtype: object

In [43]:
# duplicated
dup=df[df.duplicated(keep='first')]
dup

    Name   Age Department  Salary
5  Abebe  23.0         IT    2000

In [44]:
df.drop_duplicates()

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1   Abel  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900
4   Blen   NaN        NaN    3400

In [45]:
df

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1   Abel  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900
4   Blen   NaN        NaN    3400
5  Abebe  23.0         IT    2000

In [46]:
# apply and lamda
def multiply(x):
  return x *2
df['Age'] =df['Age'].apply(multiply)

In [47]:
df

    Name    Age Department  Salary
0  Abebe   46.0         IT    2000
1   Abel   90.0         HR    3000
2   Beti  112.0    Finance    4300
3  David   64.0         IT    5900
4   Blen    NaN        NaN    3400
5  Abebe   46.0         IT    2000

In [48]:
# lamda to back to original

df['Age']=df['Age'].apply(lambda x:x/2)

In [49]:
df

    Name   Age Department  Salary
0  Abebe  23.0         IT    2000
1   Abel  45.0         HR    3000
2   Beti  56.0    Finance    4300
3  David  32.0         IT    5900
4   Blen   NaN        NaN    3400
5  Abebe  23.0         IT    2000

In [60]:
location_info ={
  "Department":["IT","HR","Finance"],
  "Location":["Addis Ababa","Bole","Mexico"]

}

In [61]:
df2=pd.DataFrame(location_info)
df2

  Department     Location
0         IT  Addis Ababa
1         HR         Bole
2    Finance       Mexico

In [62]:
pd.concat([df,df2],axis=1)

    Name   Age Department  Salary Department     Location
0  Abebe  23.0         IT    2000         IT  Addis Ababa
1   Abel  45.0         HR    3000         HR         Bole
2   Beti  56.0    Finance    4300    Finance       Mexico
3  David  32.0         IT    5900        NaN          NaN
4   Blen   NaN        NaN    3400        NaN          NaN
5  Abebe  23.0         IT    2000        NaN          NaN

In [63]:
# merge
pd.merge(df,df2,on="Department")

    Name   Age Department  Salary     Location
0  Abebe  23.0         IT    2000  Addis Ababa
1   Abel  45.0         HR    3000         Bole
2   Beti  56.0    Finance    4300       Mexico
3  David  32.0         IT    5900  Addis Ababa
4  Abebe  23.0         IT    2000  Addis Ababa

In [8]:
# import data

data = pd.read_csv("/home/bonsa/Documents/data-analyst/python_for_analyst/data/Housing.csv")
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [9]:
data.shape

(545, 13)

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [6]:
restaurant_data = pd.read_csv("Zomato Restaurant Dataset.csv")
restaurant_data

FileNotFoundError: [Errno 2] No such file or directory: 'Zomato Restaurant Dataset.csv'

In [73]:
restaurant_data.shape

(9551, 21)

In [75]:
restaurant_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [76]:
restaurant_data.describe()

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [ ]:
restaurant_data.